version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M
